version: "3.6"

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    links:
      - "db:postgres"
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    command: ["sh", "-c", "while :; do  sleep 1; done"]
    env_file: app.env.dev
  db:
    image: postgres:9.4
    env_file: postgres.env.dev
