// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type CreateAccountantInput struct {
	CondoID     string         `json:"condoID"`
	AccountID   string         `json:"accountID"`
	Description string         `json:"description"`
	File        graphql.Upload `json:"file"`
}

type Todo struct {
	ID string `json:"id"`
}
