// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/cucumber/godog/cmd/godog"
	_ "github.com/gojuno/minimock/v3/cmd/minimock"
	_ "github.com/golang/mock/mockgen"
	_ "github.com/golang/protobuf/protoc-gen-go"
	_ "github.com/golangci/golangci-lint/cmd/golangci-lint"
	_ "github.com/hexdigest/gounit/cmd/gounit"
	_ "github.com/magefile/mage"
	_ "github.com/srikrsna/protoc-gen-mock"
	_ "github.com/uber/prototool/cmd/prototool"
	_ "gotest.tools/gotestsum"
	_ "mvdan.cc/gofumpt"
)

// If you want to use tools, please run the following command:
//  go generate ./tools.go
//
//go:generate go build -v -o=./bin/godog github.com/cucumber/godog/cmd/godog
//go:generate go build -v -o=./bin/minimock github.com/gojuno/minimock/v3/cmd/minimock
//go:generate go build -v -o=./bin/mockgen github.com/golang/mock/mockgen
//go:generate go build -v -o=./bin/protoc-gen-go github.com/golang/protobuf/protoc-gen-go
//go:generate go build -v -o=./bin/golangci-lint github.com/golangci/golangci-lint/cmd/golangci-lint
//go:generate go build -v -o=./bin/gounit github.com/hexdigest/gounit/cmd/gounit
//go:generate go build -v -o=./bin/mage github.com/magefile/mage
//go:generate go build -v -o=./bin/protoc-gen-mock github.com/srikrsna/protoc-gen-mock
//go:generate go build -v -o=./bin/prototool github.com/uber/prototool/cmd/prototool
//go:generate go build -v -o=./bin/gotestsum gotest.tools/gotestsum
//go:generate go build -v -o=./bin/gofumpt mvdan.cc/gofumpt
